[project]
name = "bird-roundness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "cloudflare>=5.6.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "opencv-python>=5.0.0.93",
    "pathlib>=1.0.1",
    "pillow>=12.3.0",
    "plotly>=6.9.0",
    "requests>=2.34.2",
    "sam3>=0.0.1",
    "selenium>=4.46.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "transformers>=5.14.1",
]
